CREATE TABLE `corroboration_findings` (
	`id` text PRIMARY KEY,
	`investigation_id` text NOT NULL,
	`graph_version` text NOT NULL,
	`finding_type` text NOT NULL,
	`kind` text NOT NULL,
	`entity_ids` text NOT NULL,
	`location_ids` text NOT NULL,
	`window_start` text,
	`window_end` text,
	`value` text NOT NULL,
	`method` text NOT NULL,
	`explanation` text NOT NULL,
	`classification` text NOT NULL,
	`evidence_item_ids` text NOT NULL,
	`supporting_record_ids` text NOT NULL,
	`provenance_source` text NOT NULL,
	`provenance_location` text NOT NULL,
	`provenance_method` text NOT NULL,
	`provenance_confidence` real NOT NULL,
	`provenance_processing_history` text NOT NULL,
	`provenance_timestamp` text NOT NULL,
	CONSTRAINT `fk_corroboration_findings_investigation_id_investigations_id_fk` FOREIGN KEY (`investigation_id`) REFERENCES `investigations`(`id`)
);
