CREATE TABLE `dossiers` (
	`id` text PRIMARY KEY,
	`investigation_id` text NOT NULL,
	`investigation_name` text NOT NULL,
	`graph_version` text NOT NULL,
	`report_version` text NOT NULL,
	`title` text NOT NULL,
	`generated_at` text NOT NULL,
	`synthetic_data_only` integer NOT NULL,
	`human_verification_required` integer NOT NULL,
	`ai_synthesis_available` integer NOT NULL,
	`ai_synthesis_note` text NOT NULL,
	`sections` text NOT NULL,
	`copilot_excerpts` text NOT NULL,
	`limitations` text NOT NULL,
	`counts` text NOT NULL,
	`provenance_source` text NOT NULL,
	`provenance_location` text NOT NULL,
	`provenance_method` text NOT NULL,
	`provenance_confidence` real NOT NULL,
	`provenance_processing_history` text NOT NULL,
	`provenance_timestamp` text NOT NULL,
	CONSTRAINT `fk_dossiers_investigation_id_investigations_id_fk` FOREIGN KEY (`investigation_id`) REFERENCES `investigations`(`id`)
);
